# Cloud Build — Build & Deploy Lumen Pipeline
#
# Usage:
#   # Manual trigger (recommended for dev):
#   gcloud builds submit \
#     --config infrastructure/cloudbuild.yaml \
#     --substitutions=_REGION=us-central1,_SERVICE_NAME=lumen-pipeline \
#     .
#
#   # Or set up a push-to-main trigger in Cloud Build console/Terraform.

substitutions:
  _REGION: "us-central1"
  _SERVICE_NAME: "lumen-pipeline"
  _REPO_NAME: "lumen-pipeline-docker"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

steps:
  # ── Step 1: Build the Docker image ─────────────────────────────────────
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:latest"
      - "-f"
      - "server/Dockerfile"
      - "server/"

  # ── Step 2: Push the image to Artifact Registry ────────────────────────
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}"

  # ── Step 3: Deploy to Cloud Run ────────────────────────────────────────
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:latest"

timeout: "1200s" # 20 min — Docker images with ML deps can be large
