# Cloud Build — Build & Push Lumen Base Image
#
# This builds the heavy base image containing all system packages,
# Python dependencies (~2GB of ML wheels), and PartCrafter. The
# application Dockerfile inherits from this image and only copies
# app code — cutting builds from 15-30 min to 1-2 min.
#
# Manual usage:
#   gcloud builds submit \
#     --config infrastructure/cloudbuild-base.yaml \
#     --project=lumen-pipeline --region=us-east4 \
#     server/
#
# Rebuild triggers:
#   - pyproject.toml or uv.lock changes
#   - Weekly schedule (catches OS security patches + dependency updates)
#   - Manual when CUDA/Python version changes

substitutions:
  _BASE_IMAGE: "us-east4-docker.pkg.dev/lumen-pipeline/lumen-pipeline-docker/lumen-base"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

steps:
  # ── Step 1: Pull previous base for layer cache ───────────────────
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - "docker pull ${_BASE_IMAGE}:latest || true"

  # ── Step 2: Build base image with cache ──────────────────────────
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--cache-from"
      - "${_BASE_IMAGE}:latest"
      - "-t"
      - "${_BASE_IMAGE}:latest"
      - "-f"
      - "Dockerfile.base"
      - "."
    env:
      - "DOCKER_BUILDKIT=1"

  # ── Step 3: Push ─────────────────────────────────────────────────
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_BASE_IMAGE}:latest"]

images:
  - "${_BASE_IMAGE}:latest"

timeout: "2400s"  # 40 min — first build is slow; cached rebuilds are ~5-10 min
