# Cloud Build — Build & Push Lumen Pipeline Image
#
# Usage:
#   gcloud builds submit \
#     --config infrastructure/cloudbuild.yaml \
#     --substitutions=COMMIT_SHA=$(git rev-parse --short HEAD) \
#     --project=lumen-pipeline --region=us-east4 \
#     .
#
# Layer caching:
#   Step 1 pulls the previous :latest image so Docker can reuse unchanged
#   layers via --cache-from. Code-only changes (no pyproject.toml/uv.lock
#   edits) skip the entire dependency layer → ~30-60s builds instead of 15min.
#
# Deploy separately via:
#   gcloud run deploy lumen-pipeline --image=$_IMAGE:$COMMIT_SHA ...
#   (or terraform apply)
#
# GPU + Secret Manager config lives in Terraform, not here.

substitutions:
  _IMAGE: "us-east4-docker.pkg.dev/lumen-pipeline/lumen-pipeline-docker/lumen-pipeline"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

steps:
  # ── Step 1: Pull previous image for layer cache ────────────────────────
  # Fails silently on first-ever build (no :latest exists yet).
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - "docker pull ${_IMAGE}:latest || true"

  # ── Step 2: Build with --cache-from ────────────────────────────────────
  # Docker compares each layer's cache key (instruction + input files).
  # If pyproject.toml/uv.lock haven't changed, the 2GB+ dependency layer
  # is reused from the pulled image — only app/ code layer rebuilds.
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--cache-from"
      - "${_IMAGE}:latest"
      - "-t"
      - "${_IMAGE}:$COMMIT_SHA"
      - "-t"
      - "${_IMAGE}:latest"
      - "-f"
      - "server/Dockerfile"
      - "server/"
    env:
      - "DOCKER_BUILDKIT=1"

  # ── Step 3: Push commit-SHA tag ────────────────────────────────────────
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE}:$COMMIT_SHA"]

  # ── Step 4: Push :latest tag (cache source for next build) ─────────────
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE}:latest"]

images:
  - "${_IMAGE}:$COMMIT_SHA"
  - "${_IMAGE}:latest"

timeout: "1200s"  # 20 min — first build downloads ~2GB of ML wheels
