# Cloud Build — Build & Push Lumen Pipeline Image
#
# Usage:
#   gcloud builds submit \
#     --config infrastructure/cloudbuild.yaml \
#     --substitutions=COMMIT_SHA=$(git rev-parse --short HEAD) \
#     --project=lumen-pipeline --region=us-east4 \
#     .
#
# Layer caching:
#   Step 1 pulls the previous :latest image so Docker can reuse unchanged
#   layers via --cache-from. Code-only changes (no pyproject.toml/uv.lock
#   edits) skip the entire dependency layer → ~30-60s builds instead of 15min.
#
# Deploy separately via:
#   gcloud run deploy lumen-pipeline --image=$_IMAGE:$COMMIT_SHA ...
#   (or terraform apply)
#
# GPU + Secret Manager config lives in Terraform, not here.

substitutions:
  _IMAGE: "us-east4-docker.pkg.dev/lumen-pipeline/lumen-pipeline-docker/lumen-pipeline"
  _BASE_IMAGE: "us-east4-docker.pkg.dev/lumen-pipeline/lumen-pipeline-docker/lumen-base"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

steps:
  # ── Step 0a: Frontend tests ────────────────────────────────────────────
  # Gate: if tests fail, the build stops before Docker build.
  - name: "node:22-slim"
    id: "test-frontend"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd /workspace
        npm ci --prefer-offline 2>/dev/null
        echo "── Frontend: lint + typecheck + tests ──"
        npx eslint . --quiet
        npx tsc --noEmit
        npx vitest run --reporter=dot

  # ── Step 0b: Backend tests (parallel with frontend) ────────────────────
  - name: "ghcr.io/astral-sh/uv:latest"
    id: "test-backend"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd /workspace/server
        echo "── Backend: lint + typecheck + tests ──"
        uv run ruff check app/ tests/ --quiet
        uv run ruff format --check app/ tests/ --quiet
        uv run pytest tests/ -v --timeout=30 -x
    env:
      - "UV_TORCH_BACKEND=cpu"

  # ── Step 1: Pull base image + previous app image for layer cache ──────
  # Only runs after both test steps pass.
  - name: "gcr.io/cloud-builders/docker"
    waitFor: ["test-frontend", "test-backend"]
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull ${_BASE_IMAGE}:latest || true
        docker pull ${_IMAGE}:latest || true

  # ── Step 2: Build with pre-built base image ──────────────────────────
  # The base image (lumen-base:latest) contains all dependencies.
  # This step ONLY copies app/ code → builds in 1-2 min instead of 15-30 min.
  # If the base image doesn't exist, uses the fallback in the Dockerfile ARG.
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "BASE_IMAGE=${_BASE_IMAGE}:latest"
      - "--cache-from"
      - "${_IMAGE}:latest"
      - "-t"
      - "${_IMAGE}:$COMMIT_SHA"
      - "-t"
      - "${_IMAGE}:latest"
      - "-f"
      - "server/Dockerfile"
      - "server/"
    env:
      - "DOCKER_BUILDKIT=1"

  # ── Step 3: Push commit-SHA tag ────────────────────────────────────────
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE}:$COMMIT_SHA"]

  # ── Step 4: Push :latest tag (cache source for next build) ─────────────
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE}:latest"]

images:
  - "${_IMAGE}:$COMMIT_SHA"
  - "${_IMAGE}:latest"

timeout: "1800s"  # 30 min — torchvision + ML wheels are large
