# Cloud Build — Build & Push Lumen Pipeline Image
#
# Usage:
#   gcloud builds submit \
#     --config infrastructure/cloudbuild.yaml \
#     --project=lumen-pipeline --region=us-east4 \
#     .
#
# Layer caching:
#   Step 1 pulls the previous :latest image so Docker can reuse unchanged
#   layers via --cache-from. Code-only changes (no pyproject.toml/uv.lock
#   edits) skip the entire dependency layer → ~30-60s builds instead of 15min.
#
# GPU + Secret Manager config lives in Terraform, not here.

substitutions:
  _IMAGE: "us-east4-docker.pkg.dev/lumen-pipeline/lumen-pipeline-docker/lumen-pipeline"
  _BASE_IMAGE: "us-east4-docker.pkg.dev/lumen-pipeline/lumen-pipeline-docker/lumen-base"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

steps:
  # ── Step 0: Backend tests (gate build on passing checks) ───────────────
  - name: "ghcr.io/astral-sh/uv:python3.13-bookworm-slim"
    id: "test-backend"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd /workspace/server
        echo "── Backend: lint + typecheck + tests ──"
        uv run ruff check app/ tests/ --quiet
        uv run ruff format --check app/ tests/ --quiet
        uv run mypy app/
        uv run pytest tests/ -v --timeout=30 -x
    env:
      - "UV_TORCH_BACKEND=cpu"

  # ── Step 1: Pull base image + previous app image for layer cache ──────
  - name: "gcr.io/cloud-builders/docker"
    waitFor: ["test-backend"]
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull ${_BASE_IMAGE}:latest || true
        docker pull ${_IMAGE}:latest || true

  # ── Step 2: Build with pre-built base image ──────────────────────────
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "BASE_IMAGE=${_BASE_IMAGE}:latest"
      - "--cache-from"
      - "${_IMAGE}:latest"
      - "-t"
      - "${_IMAGE}:latest"
      - "-f"
      - "server/Dockerfile"
      - "server/"
    env:
      - "DOCKER_BUILDKIT=1"

  # ── Step 3: Push :latest ─────────────────────────────────────────────
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE}:latest"]

images:
  - "${_IMAGE}:latest"

timeout: "1800s"  # 30 min
